routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);
Route::get('/home', 'Backend\HomeController@index')->name('home');
Route::get('/edit-account', 'Backend\HomeController@edit');
Route::put('/edit-account', 'Backend\HomeController@update');
Route::put('/backend/posts/restore/{post}', 'Backend\PostController@restore')->name('posts.restore');
Route::delete('/backend/posts/force-destroy/{post}', 'Backend\PostController@forceDestroy')->name('posts.force-destroy');
Route::resource('/backend/posts', 'Backend\PostController');
Route::resource('/backend/categories', 'Backend\CategoryController');
Route::get('backend/users/confirm/{user}', 'Backend\UserController@confirm')->name('users.confirm');
Route::resource('/backend/users', 'Backend\UserController');

Route::get('/', 'BlogController@index')->name('blog.index');
Route::get('/{posts}', 'BlogController@show')->name('blog.show');
Route::post('/{posts}/comments', 'CommentController@store')->name('blog.comments');
Route::get('/category/{category}', 'BlogController@getByCategory')->name('blog.category');
Route::get('/author/{author}', 'BlogController@getByAuthor')->name('blog.author');
Route::get('/tag/{tag}', 'BlogController@getByTag')->name('blog.tag');

app/Models/Post.php
<?php

namespace App\Models;

use Carbon\Carbon;
use GrahamCampbell\Markdown\Facades\Markdown;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Post extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = ['title', 'slug', 'excerpt', 'body', 'published_at', 'category_id', 'view_count', 'image'];
    protected $dates = ['published_at'];

    public function author()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function commentsNumber($label = 'Comment')
    {
        $commentsNumber = $this->comments->count();

        return $commentsNumber . " " . Str::plural($label, $commentsNumber);
    }

    public function createComment(array $data)
    {
        $this->comments()->create($data);
    }

    public function createTags($tagString)
    {
        $tags = explode(",", $tagString);
        $tagIds = [];

        foreach ($tags as $tag) {
            $newTag = Tag::firstOrCreate(
                ['slug' => Str::slug($tag, '-'), 'name' => ucwords(trim($tag))]
            );

            if (!in_array($newTag->id, $tagIds)) {
                $tagIds[] = $newTag->id;
            }
        }

        $this->tags()->sync($tagIds);
    }

    public function getImageUrlAttribute($value)
    {
        $imageUrl = null;
        if (!is_null($this->image)) {
            $directory = config('cms.image.directory');
            $imagePath = public_path() . "/{$directory}/" . $this->image;
            if (file_exists($imagePath)) $imageUrl = asset("{$directory}/" . $this->image);
        }
        return $imageUrl;
    }

    public function getImageThumbUrlAttribute($value)
    {
        $imageUrl = null;
        if (!is_null($this->image)) {
            $directory = config('cms.image.directory');
            $ext = substr(strrchr($this->image, "."), 1);
            $thumbnail = str_replace(".{$ext}", "_thumb.{$ext}", $this->image);
            $imagePath = public_path() . "/{$directory}/" . $thumbnail;
            if (file_exists($imagePath)) $imageUrl = asset("{$directory}/" . $thumbnail);
        }
        return $imageUrl;
    }

    public function getDateAttribute($value)
    {
        return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
    }

    public function getBodyHtmlAttribute($value)
    {
        return $this->body ? Markdown::convertToHtml($this->body) : null;
    }

    public function getExcerptHtmlAttribute($value)
    {
        return $this->excerpt ? Markdown::convertToHtml($this->excerpt) : null;
    }

    public function getTagsHtmlAttribute($value)
    {
        $anchors = [];
        foreach ($this->tags as $tag) {
            $anchors[] = '<a href="' . route('blog.tag', $tag->slug) . '">' . $tag->name . '</a>';
        }
        return implode(", ", $anchors);
    }

    public function getTagsListAttribute()
    {
        return $this->tags->pluck('name');
    }

    public function dateFormatted($showTimes = false)
    {
        $format = 'd/m/Y';
        if ($showTimes) $format = $format . ' H:i:s';
        return $this->created_at->format($format);
    }

    public function publishcationLabel()
    {
        if (!$this->published_at) {
            return '<span class="label label-warning">Draft</span>';
        } elseif ($this->published_at && $this->published_at->isFuture()) {
            return '<span class="label label-info">Schedule</span>';
        } else {
            return '<span class="label label-success">Published</span>';
        }
    }

    public function scopeLastestFirst($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', Carbon::now());
    }

    public function scopeScheduled($query)
    {
        return $query->where('published_at', '>', Carbon::now());
    }

    public function scopeDraft($query)
    {
        return $query->whereNull('published_at');
    }

    public function scopePopular($query)
    {
        return $query->orderBy('view_count', 'desc');
    }

    public function scopeFilter($query, $filter)
    {
        if (isset($filter['month']) && $month = $filter['month']) {
            $query->whereRaw('month(published_at) = ?', [Carbon::parse($month)->month]);
        }
        if (isset($filter['year']) && $year = $filter['year']) {
            $query->whereRaw('year(published_at) = ?', [$year]);
        }
        if (isset($filter['term']) && $term = $filter['term']) {
            $query->where(function ($q) use ($term) {
                $q->whereHas('author', function ($qr) use ($term) {
                    $qr->where('name', 'LIKE', "%{$term}%");
                });
                $q->orWhereHas('category', function ($qr) use ($term) {
                    $qr->where('title', 'LIKE', "%{$term}%");
                });
                $q->orWhere('title', 'LIKE', "%{$term}%");
                $q->orWhere('excerpt', 'LIKE', "%{$term}%");
            });
        }
    }

    public static function archives()
    {
        return static::selectRaw('count(id) as post_count, year(published_at) year, monthname(published_at) month')
            ->published()
            ->groupBy('year', 'month')
            ->orderByRaw('min(published_at) desc')
            ->get();
    }
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

class BackendController extends Controller
{
    protected $limit = 5;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('check-permissions');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryDestroyRequest;
use App\Http\Requests\CategoryStoreRequest;
use App\Http\Requests\CategoryUpdateRequest;
use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;

class CategoryController extends BackendController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::with('posts')->orderBy('title')->paginate($this->limit);
        $categoriesCount = Category::count();
        return view('backend.categories.index', compact('categories', 'categoriesCount'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = new Category();
        return view("backend.categories.create", compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryStoreRequest $request)
    {
        Category::create($request->all());

        return redirect('/backend/categories')->with('message', 'New category was created!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view("backend.categories.edit", compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryUpdateRequest $request, $id)
    {
        Category::findOrFail($id)->update($request->all());

        return redirect('/backend/categories')->with('message', 'New category was updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(CategoryDestroyRequest $request, $id)
    {
        Post::withTrashed()->where('category_id', $id)->update(['category_id' => config('cms.default_category_id')]);;
        Category::findOrFail($id)->delete();
        return redirect('/backend/categories')->with('message', 'New category was deleted!');
    }
}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\AccountUpdateRequest;
use App\Http\Requests\UserUpdateRequest;
use Illuminate\Http\Request;

class HomeController extends BackendController
{


    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('backend.home.home');
    }

    public function edit(Request $request)
    {
        $user = $request->user();
        return view('backend.home.edit', compact('user'));
    }

    public function update(AccountUpdateRequest $request)
    {
        $user = $request->user();
        $user->update($request->all());

        return redirect()->back()->with('message', 'Account was update successfully!');
    }
}

app/Http/Controllers/Backend/PostController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests\PostRequest;
use App\Models\Post;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;

class PostController extends BackendController
{
    protected $uploadPath;

    public function __construct()
    {
        parent::__construct();
        $this->uploadPath = public_path(config('cms.image.directory'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $onlyTrashed = FALSE;

        if (($status = $request->get('status')) && $status == 'trash') {
            $posts = Post::onlyTrashed()->with('category', 'author')->latest()->paginate($this->limit);
            $postsCount = Post::onlyTrashed()->count();
            $onlyTrashed = TRUE;
        } elseif ($status == 'published') {
            $posts = Post::published()->with('category', 'author')->latest()->paginate($this->limit);
            $postsCount = Post::published()->count();
        } elseif ($status == 'scheduled') {
            $posts = Post::scheduled()->with('category', 'author')->latest()->paginate($this->limit);
            $postsCount = Post::scheduled()->count();
        } elseif ($status == 'draft') {
            $posts = Post::draft()->with('category', 'author')->latest()->paginate($this->limit);
            $postsCount = Post::draft()->count();
        } elseif ($status == 'own') {
            $posts = $request->user()->posts()->with('category', 'author')->latest()->paginate($this->limit);
            $postsCount = $request->user()->posts()->count();
        } else {
            $posts = Post::with('category', 'author')->latest()->paginate($this->limit);
            $postsCount = Post::count();
        }

        $statusList = $this->getStatusList($request);

        return view('backend.posts.index', compact('posts', 'postsCount', 'onlyTrashed', 'statusList'));
    }

    private function getStatusList($request)
    {
        return [
            'own' => $request->user()->posts()->count(),
            'all' => Post::count(),
            'published' => Post::published()->count(),
            'scheduled' => Post::scheduled()->count(),
            'draft' => Post::draft()->count(),
            'trash' => Post::onlyTrashed()->count()
        ];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Post $post
     * @return \Illuminate\Http\Response
     */
    public function create(Post $post)
    {
        return view('backend.posts.create', compact('post'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        $data = $this->handleRequest($request);
        $newPost = $request->user()->posts()->create($data);
        $newPost->createTags($data["post_tags"]);
        return redirect('/backend/posts')->with('message', 'Your post was created success!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        return view('backend.posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, $id)
    {
        $post = Post::findOrFail($id);
        $oldImage = $post->image;
        $data = $this->handleRequest($request);
        $post->update($data);
        $post->createTags($data['post_tags']);
        if ($oldImage !== $post->image) {
            $this->removeImage($oldImage);
        }
        return redirect('/backend/posts')->with('message', 'Your post was updated success!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::findOrFail($id)->delete();

        return redirect('/backend/posts')->with('trash-message', ['Your post moved to Trash!', $id]);
    }

    public function forceDestroy($id)
    {
        $post = Post::withTrashed()->findOrFail($id);
        $post->forceDelete();
        $this->removeImage($post->image);
        return redirect('backend/posts?status=trash')->with('message', 'Your post has been deleted success!');
    }

    public function restore($id)
    {
        $post = Post::withTrashed()->findOrFail($id);
        $post->restore();

        return redirect()->back()->with('message', 'Your post has been moved from the Trash!');
    }

    private function removeImage($image)
    {
        if (!empty($image)) {
            $imagePath = $this->uploadPath . '/' . $image;
            $ext = substr(strrchr($image, '.'), 1);
            $thumbnail = str_replace(".{$ext}", "_thumb.{$ext}", $image);
            $thumbnailPath = $this->uploadPath . '/' . $thumbnail;
            if (file_exists($imagePath)) unlink($imagePath);
            if (file_exists($thumbnailPath)) unlink($thumbnailPath);
        }
    }

    private function handleRequest($request)
    {
        $data = $request->all();

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $fileName = $image->getClientOriginalName();
            $destination = $this->uploadPath;

            $successUploaded = $image->move($destination, $fileName);

            if ($successUploaded) {
                $width = config('cms.image.thumbnail.width');
                $height = config('cms.image.thumbnail.height');
                $extension = $image->getClientOriginalExtension();
                $thumbnail = str_replace(".{$extension}", "_thumb.{$extension}", $fileName);

                Image::make($destination . '/' . $fileName)
                    ->resize($width, $height)
                    ->save($destination . '/' . $thumbnail);
            }

            $data['image'] = $fileName;
        }

        return $data;
    }
}

resources/views/backend/posts/create.blade.php
@extends('layouts.backend.main')
@section('title', 'MyBlog | Add New Post')
@section('content')
    <section class="content-header">
        <h1>
            Posts
            <small>Add new Post</small>
        </h1>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i> Dashboard</a>
            </li>
            <li>
                <a href="{{ route('posts.index') }}">Blog</a>
            </li>
            <li class="active">
                Add New Posts
            </li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            {!! Form::model($post, [
                           'method' => 'POST',
                           'route' => 'posts.store',
                           'files' => TRUE,
                           'id' => 'post-form'
                       ]) !!}
            @include('backend.posts.form')
            {!! Form::close() !!}
        </div>
        <!-- ./row -->
    </section>
    <!-- /.content -->
@endsection
@include('backend.posts.script')

resources/views/backend/posts/edit.blade.php
@extends('layouts.backend.main')
@section('title', 'MyBlog | Edit Post')
@section('content')
    <section class="content-header">
        <h1>
            Posts
            <small>Edit Post</small>
        </h1>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i> Dashboard</a>
            </li>
            <li>
                <a href="{{ route('posts.index') }}">Blog</a>
            </li>
            <li class="active">
                Add New Posts
            </li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            {!! Form::model($post, [
                           'method' => 'PUT',
                           'route' => ['posts.update', $post->id],
                           'files' => TRUE,
                           'id' => 'post-form'
                       ]) !!}
            @include('backend.posts.form')
            {!! Form::close() !!}
        </div>
        <!-- ./row -->
    </section>
    <!-- /.content -->
@endsection
@include('backend.posts.script')

resources/views/backend/posts/form.blade.php
<div class="col-xs-9">
    <div class="box">
        <div class="box-body ">
            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                {!! Form::label('title') !!}
                {!! Form::text('title', null, ['class' => 'form-control']) !!}

                @if ($errors->has('title'))
                    <span class="help-block">{{ $errors->first('title') }}</span>
                @endif
            </div>
            <div class="form-group {{ $errors->has('slug') ? 'has-error' : '' }}">
                {!! Form::label('slug') !!}
                {!! Form::text('slug', null, ['class' => 'form-control']) !!}

                @if ($errors->has('slug'))
                    <span class="help-block">{{ $errors->first('slug') }}</span>
                @endif
            </div>
            <div class="form-group excerpt {{ $errors->has('excerpt') ? 'has-error' : '' }}">
                {!! Form::label('excerpt') !!}
                {!! Form::textarea('excerpt', null, ['class' => 'form-control']) !!}

                @if ($errors->has('excerpt'))
                    <span class="help-block">{{ $errors->first('excerpt') }}</span>
                @endif
            </div>
            <div class="form-group {{ $errors->has('body') ? 'has-error' : '' }}">
                {!! Form::label('body') !!}
                {!! Form::textarea('body', null, ['class' => 'form-control']) !!}

                @if ($errors->has('body'))
                    <span class="help-block">{{ $errors->first('body') }}</span>
                @endif
            </div>


            <hr>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
</div>
<div class="col-xs-3">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Publish</h3>
        </div>
        <div class="box-body">
            <div class="form-group {{ $errors->has('published_at') ? 'has-error' : '' }}">
                {!! Form::label('published_at', 'Publish Date') !!}
                <div class='input-group date' id='datetimepicker1'>
                    {!! Form::text('published_at', null, ['class' => 'form-control', 'placeholder' => 'd-m-Y H:i:s']) !!}
                    <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                </div>

                @if ($errors->has('published_at'))
                    <span class="help-block">{{ $errors->first('published_at') }}</span>
                @endif
            </div>
        </div>
        <div class="box-footer">
            <div class="pull-left">
                <a id="draft-btn" class="btn btn-primary">Save Draft</a>
            </div>
            <div class="pull-right">
                {!! Form::submit('publish', ['class' => 'btn btn-primary']) !!}
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Category</h3>
        </div>
        <div class="box-body">
            <div class="form-group {{ $errors->has('category_id') ? 'has-error' : '' }}">
                {!! Form::select('category_id', App\Models\Category::pluck('title', 'id'), null,
                ['class' => 'form-control', 'placeholder' => 'Choose category']) !!}

                @if ($errors->has('category_id'))
                    <span class="help-block">{{ $errors->first('category_id') }}</span>
                @endif
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Feature Image</h3>
        </div>
        <div class="box-body text-center">
            <div class="form-group {{ $errors->has('image') ? 'has-error' : '' }}">
                <div class="fileinput fileinput-new" data-provides="fileinput">
                    <div class="fileinput-new img-thumbnail" style="width: 200px; height: 150px;">
                        <img src="{{ isset($post->image_thumb_url) ? $post->image_thumb_url : 'http://placehold.it/200x150&text=No_Image' }}" alt="...">
                    </div>
                    <div class="fileinput-preview fileinput-exists img-thumbnail"
                         style="max-width: 200px; max-height: 150px;"></div>
                    <div>
                                    <span class="btn btn-outline-secondary btn-file"><span class="fileinput-new">Select image</span><span
                                            class="fileinput-exists">Change</span>{!! Form::file('image') !!}</span>
                        <a href="#" class="btn btn-outline-secondary fileinput-exists"
                           data-dismiss="fileinput">Remove</a>
                    </div>
                </div>
                @if ($errors->has('image'))
                    <span class="help-block">{{ $errors->first('image') }}</span>
                @endif
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Tags</h3>
        </div>
        <div class="box-body">
            <div class="form-group">
                {!! Form::text('post_tags', null, ['class' => 'form-control']) !!}
            </div>
        </div>
    </div>
</div>

resources/views/backend/posts/index.blade.php
@extends('layouts.backend.main')
@section('title', 'MyBlog | Posts')
@section('content')
    <section class="content-header">
        <h1>
            Posts
            <small>All Blog Posts</small>
        </h1>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i> Dashboard</a>
            </li>
            <li>
                <a href="{{ route('posts.index') }}">Blog</a>
            </li>
            <li class="active">
                Posts
            </li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <div class="pull-left">
                            <a href="{{ route('posts.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add
                                New Post</a>
                        </div>
                        <div class="pull-right">
                            @php $links = [] @endphp
                            @foreach($statusList as $key => $value)
                                @if($value)
                                    @php $selected = Request::get('status') == $key ? 'selected-status' : '' @endphp
                                    @php $links[] = "<a class=\"{$selected}\" href=\"?status={$key}\">".ucwords($key)."({$value})</a>" @endphp
                                @endif
                            @endforeach
                            {!! implode(' | ', $links) !!}
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body ">
                        @include('backend.partials.message')
                        @if (!$postsCount)
                            <div class="alert alert-warning">
                                <strong>No record found</strong>
                            </div>
                        @else
                            @if($onlyTrashed)
                                @include('backend.posts.table-trash')
                            @else
                                @include('backend.posts.table')
                            @endif
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                        <div class="pull-left">
                            {!! $posts->appends(Request::query())->links() !!}
                        </div>
                        <div class="pull-right">
                            <small>{{ $postsCount }} {{ Str::plural('Item', $postsCount) }}</small>
                        </div>
                    </div>
                    @endif
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- ./row -->
    </section>
    <!-- /.content -->
@endsection
@push('scripts')
    <script type="text/javascript">
        $('ul.pagination').addClass('no-margin pagination-sm');
    </script>
@endpush

resources/views/backend/posts/message.blade.php
@if (session('message'))
    <div class="alert alert-success">
        {{ session('message') }}
    </div>
@elseif(session('trash-message'))
    @php list($message, $postId) = session('trash-message') @endphp
    {!! Form::open(['method' => 'PUT', 'route' => ['posts.restore', $postId]]) !!}
    <div class="alert alert-info">
        {{ $message }}
        <button type="submit" class="btn btn-warning"><i class="fa fa-undo"></i>Undo</button>
    </div>
    {!! Form::close() !!}
@endif

resources/views/backend/posts/script.blade.php
@push('styles')
    <link rel="stylesheet" href="/backend/plugins/tag-editor/jquery.tag-editor.css">
@endpush
@push('scripts')
    <script src="/backend/plugins/tag-editor/jquery.caret.min.js"></script>
    <script src="/backend/plugins/tag-editor/jquery.tag-editor.min.js"></script>
    <script type="text/javascript">
        let options = {};
        @if($post->exists)
            options = {
            initialTags: {!! $post->tags_list !!},
        };
        @endif
        $('input[name=post_tags]').tagEditor(options);
        $('ul.pagination').addClass('no-margin pagination-sm');
        $('#title').on('blur', function () {
            let theTitle = this.value.toLowerCase().trim();
            let slugInput = $('#slug');
            let theSlug = theTitle.replace(/[^a-z0-9-]+/g, '-')
                .replace(/\-\-+/g, '-')
                .replace(/^-+|-+$/g, '')
                .replace(/&/g, '-and-');
            slugInput.val(theSlug);
        });

        let simplemde1 = new SimpleMDE({element: $('#excerpt')[0]})
        let simplemde2 = new SimpleMDE({element: $('#body')[0]})

        $('#datetimepicker1').datetimepicker({
            format: 'DD-MM-YYYY HH:mm:ss',
            showClear: true
        });

        $('#draft-btn').click(function (e) {
            e.preventDefault();
            $('#published_at').val('');
            $('#post-form').submit();
        });
    </script>
@endpush