routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);
Route::get('/home', 'Backend\HomeController@index')->name('home');
Route::get('/edit-account', 'Backend\HomeController@edit');
Route::put('/edit-account', 'Backend\HomeController@update');
Route::put('/backend/posts/restore/{post}', 'Backend\PostController@restore')->name('posts.restore');
Route::delete('/backend/posts/force-destroy/{post}', 'Backend\PostController@forceDestroy')->name('posts.force-destroy');
Route::resource('/backend/posts', 'Backend\PostController');
Route::resource('/backend/categories', 'Backend\CategoryController');
Route::get('backend/users/confirm/{user}', 'Backend\UserController@confirm')->name('users.confirm');
Route::resource('/backend/users', 'Backend\UserController');

Route::get('/', 'BlogController@index')->name('blog.index');
Route::get('/{posts}', 'BlogController@show')->name('blog.show');
Route::post('/{posts}/comments', 'CommentController@store')->name('blog.comments');
Route::get('/category/{category}', 'BlogController@getByCategory')->name('blog.category');
Route::get('/author/{author}', 'BlogController@getByAuthor')->name('blog.author');
Route::get('/tag/{tag}', 'BlogController@getByTag')->name('blog.tag');

app/Models/Post.php
<?php

namespace App\Models;

use Carbon\Carbon;
use GrahamCampbell\Markdown\Facades\Markdown;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Post extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = ['title', 'slug', 'excerpt', 'body', 'published_at', 'category_id', 'view_count', 'image'];
    protected $dates = ['published_at'];

    public function author()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function commentsNumber($label = 'Comment')
    {
        $commentsNumber = $this->comments->count();

        return $commentsNumber . " " . Str::plural($label, $commentsNumber);
    }

    public function createComment(array $data)
    {
        $this->comments()->create($data);
    }

    public function createTags($tagString)
    {
        $tags = explode(",", $tagString);
        $tagIds = [];

        foreach ($tags as $tag) {
            $newTag = Tag::firstOrCreate(
                ['slug' => Str::slug($tag, '-'), 'name' => ucwords(trim($tag))]
            );

            if (!in_array($newTag->id, $tagIds)) {
                $tagIds[] = $newTag->id;
            }
        }

        $this->tags()->sync($tagIds);
    }

    public function getImageUrlAttribute($value)
    {
        $imageUrl = null;
        if (!is_null($this->image)) {
            $directory = config('cms.image.directory');
            $imagePath = public_path() . "/{$directory}/" . $this->image;
            if (file_exists($imagePath)) $imageUrl = asset("{$directory}/" . $this->image);
        }
        return $imageUrl;
    }

    public function getImageThumbUrlAttribute($value)
    {
        $imageUrl = null;
        if (!is_null($this->image)) {
            $directory = config('cms.image.directory');
            $ext = substr(strrchr($this->image, "."), 1);
            $thumbnail = str_replace(".{$ext}", "_thumb.{$ext}", $this->image);
            $imagePath = public_path() . "/{$directory}/" . $thumbnail;
            if (file_exists($imagePath)) $imageUrl = asset("{$directory}/" . $thumbnail);
        }
        return $imageUrl;
    }

    public function getDateAttribute($value)
    {
        return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
    }

    public function getBodyHtmlAttribute($value)
    {
        return $this->body ? Markdown::convertToHtml($this->body) : null;
    }

    public function getExcerptHtmlAttribute($value)
    {
        return $this->excerpt ? Markdown::convertToHtml($this->excerpt) : null;
    }

    public function getTagsHtmlAttribute($value)
    {
        $anchors = [];
        foreach ($this->tags as $tag) {
            $anchors[] = '<a href="' . route('blog.tag', $tag->slug) . '">' . $tag->name . '</a>';
        }
        return implode(", ", $anchors);
    }

    public function getTagsListAttribute()
    {
        return $this->tags->pluck('name');
    }

    public function dateFormatted($showTimes = false)
    {
        $format = 'd/m/Y';
        if ($showTimes) $format = $format . ' H:i:s';
        return $this->created_at->format($format);
    }

    public function publishcationLabel()
    {
        if (!$this->published_at) {
            return '<span class="label label-warning">Draft</span>';
        } elseif ($this->published_at && $this->published_at->isFuture()) {
            return '<span class="label label-info">Schedule</span>';
        } else {
            return '<span class="label label-success">Published</span>';
        }
    }

    public function scopeLastestFirst($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', Carbon::now());
    }

    public function scopeScheduled($query)
    {
        return $query->where('published_at', '>', Carbon::now());
    }

    public function scopeDraft($query)
    {
        return $query->whereNull('published_at');
    }

    public function scopePopular($query)
    {
        return $query->orderBy('view_count', 'desc');
    }

    public function scopeFilter($query, $filter)
    {
        if (isset($filter['month']) && $month = $filter['month']) {
            $query->whereRaw('month(published_at) = ?', [Carbon::parse($month)->month]);
        }
        if (isset($filter['year']) && $year = $filter['year']) {
            $query->whereRaw('year(published_at) = ?', [$year]);
        }
        if (isset($filter['term']) && $term = $filter['term']) {
            $query->where(function ($q) use ($term) {
                $q->whereHas('author', function ($qr) use ($term) {
                    $qr->where('name', 'LIKE', "%{$term}%");
                });
                $q->orWhereHas('category', function ($qr) use ($term) {
                    $qr->where('title', 'LIKE', "%{$term}%");
                });
                $q->orWhere('title', 'LIKE', "%{$term}%");
                $q->orWhere('excerpt', 'LIKE', "%{$term}%");
            });
        }
    }

    public static function archives()
    {
        return static::selectRaw('count(id) as post_count, year(published_at) year, monthname(published_at) month')
            ->published()
            ->groupBy('year', 'month')
            ->orderByRaw('min(published_at) desc')
            ->get();
    }
}

app/Models/User.php
<?php

namespace App\Models;

use GrahamCampbell\Markdown\Facades\Markdown;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'slug',
        'bio'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class, 'author_id', 'id');
    }

    public function gravatar()
    {
        $email = $this->email;
        $default = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/User_icon-cp.svg/200px-User_icon-cp.svg.png";
        $size = 40;

        return "https://www.gravatar.com/avatar/" . md5(strtolower(trim($email))) . "?d=" . urlencode($default) . "&s=" . $size;
    }

    public function getBioHtmlAttribute()
    {
        return $this->bio ? Markdown::convertToHtml($this->bio) : null;
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function setPasswordAttribute($value)
    {
        if (!empty($value)) $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use App\Models\Tag;
use App\Models\User;
use Illuminate\Http\Request;

class BlogController extends Controller
{

    protected $limit = 3;

    public function index()
    {
        $posts = Post::with('author', 'category', 'tags', 'comments')
            ->lastestFirst()
            ->published()
            ->filter(request()->only(['term', 'year', 'month']))
            ->simplePaginate($this->limit);
        return view('blog.index', compact('posts'));
    }

    public function show(Post $post)
    {
        $post->increment('view_count');
        $postComments = $post->comments()->simplePaginate(3);
        return view('blog.show', compact('post', 'postComments'));
    }

    public function getByCategory(Category $category)
    {
        $categoryName = $category->title;
        $posts = $category->posts()->with('author', 'tags', 'comments')->lastestFirst()->published()->simplePaginate($this->limit);
        return view('blog.index', compact('posts', 'categoryName'));
    }

    public function getByAuthor(User $author)
    {
        $authorName = $author->name;
        $posts = $author->posts()->with('category', 'tags', 'comments')->lastestFirst()->published()->simplePaginate($this->limit);
        return view('blog.index', compact('posts', 'authorName'));
    }

    public function getByTag(Tag $tag)
    {
        $tagName = $tag->name;
        $posts = $tag->posts()->with('author', 'category', 'comments')->lastestFirst()->published()->simplePaginate($this->limit);
        return view('blog.index', compact('posts', 'tagName'));
    }
}

resources/views/blog/alert.blade.php
@if (isset($categoryName))
    <div class="alert alert-info">
        <p>Category: <strong>{{ $categoryName }}</strong></p>
    </div>
@endif
@if (isset($tagName))
    <div class="alert alert-info">
        <p>Tag: <strong>{{ $tagName }}</strong></p>
    </div>
@endif
@if (isset($authorName))
    <div class="alert alert-info">
        <p>Author: <strong>{{ $authorName }}</strong></p>
    </div>
@endif
@if ($term = request('term'))
    <div class="alert alert-info">
        <p>Search Results for: <strong>{{ $term }}</strong></p>
    </div>
@endif

resources/views/blog/comments.blade.php
<article class="post-comments" id="post-comments">
    <h3><i class="fa fa-comments"></i> {{ $post->commentsNumber('Comment')}}</h3>

    <div class="comment-body padding-10">
        <ul class="comments-list">
            @foreach($post->comments as $comment)
                <li class="comment-item">
                    <div class="comment-heading clearfix">
                        <div class="comment-author-meta">
                            <h4>{{ $comment->author_name }} <small>{{ $comment->date }}</small></h4>
                        </div>
                    </div>
                    <div class="comment-content">
                        {!! $comment->body_html !!}
                    </div>
                </li>
            @endforeach

            {{--            <li class="comment-item">--}}
            {{--                <div class="comment-heading clearfix">--}}
            {{--                    <div class="comment-author-meta">--}}
            {{--                        <h4>John Doe <small>January 14, 2016</small></h4>--}}
            {{--                    </div>--}}
            {{--                </div>--}}
            {{--                <div class="comment-content">--}}
            {{--                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla--}}
            {{--                        est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id--}}
            {{--                        ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>--}}
            {{--                    <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non--}}
            {{--                        facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum--}}
            {{--                        reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>--}}

            {{--                    <ul class="comments-list-children">--}}
            {{--                        <li class="comment-item">--}}
            {{--                            <div class="comment-heading clearfix">--}}
            {{--                                <div class="comment-author-meta">--}}
            {{--                                    <h4>John Doe <small>January 14, 2016</small></h4>--}}
            {{--                                </div>--}}
            {{--                            </div>--}}
            {{--                            <div class="comment-content">--}}
            {{--                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio--}}
            {{--                                    nesciunt nulla est, atque ratione nostrum cumque ducimus maxime,--}}
            {{--                                    amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda--}}
            {{--                                    magnam doloribus!</p>--}}
            {{--                                <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea--}}
            {{--                                    ab non facilis enim vitae inventore laborum hic unde esse debitis.--}}
            {{--                                    Adipisci nostrum reprehenderit explicabo, non molestias aliquid--}}
            {{--                                    quibusdam tempore. Vel.</p>--}}
            {{--                            </div>--}}
            {{--                        </li>--}}

            {{--                        <li class="comment-item">--}}
            {{--                            <div class="comment-heading clearfix">--}}
            {{--                                <div class="comment-author-meta">--}}
            {{--                                    <h4>John Doe <small>January 14, 2016</small></h4>--}}
            {{--                                </div>--}}
            {{--                            </div>--}}
            {{--                            <div class="comment-content">--}}
            {{--                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio--}}
            {{--                                    nesciunt nulla est, atque ratione nostrum cumque ducimus maxime,--}}
            {{--                                    amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda--}}
            {{--                                    magnam doloribus!</p>--}}
            {{--                                <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea--}}
            {{--                                    ab non facilis enim vitae inventore laborum hic unde esse debitis.--}}
            {{--                                    Adipisci nostrum reprehenderit explicabo, non molestias aliquid--}}
            {{--                                    quibusdam tempore. Vel.</p>--}}

            {{--                                <ul class="comments-list-children">--}}
            {{--                                    <li class="comment-item">--}}
            {{--                                        <div class="comment-heading clearfix">--}}
            {{--                                            <div class="comment-author-meta">--}}
            {{--                                                <h4>John Doe <small>January 14, 2016</small></h4>--}}
            {{--                                            </div>--}}
            {{--                                        </div>--}}
            {{--                                        <div class="comment-content">--}}
            {{--                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.--}}
            {{--                                                Optio nesciunt nulla est, atque ratione nostrum cumque--}}
            {{--                                                ducimus maxime, amet enim tempore ipsam. Id ea, veniam--}}
            {{--                                                ipsam perspiciatis assumenda magnam doloribus!</p>--}}
            {{--                                            <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae--}}
            {{--                                                commodi ea ab non facilis enim vitae inventore laborum--}}
            {{--                                                hic unde esse debitis. Adipisci nostrum reprehenderit--}}
            {{--                                                explicabo, non molestias aliquid quibusdam tempore.--}}
            {{--                                                Vel.</p>--}}
            {{--                                        </div>--}}
            {{--                                    </li>--}}
            {{--                                </ul>--}}
            {{--                            </div>--}}
            {{--                        </li>--}}
            {{--                    </ul>--}}
            {{--                </div>--}}
            {{--            </li>--}}
        </ul>

        <nav>
            {!! $postComments->links() !!}
        </nav>
    </div>

    <div class="comment-footer padding-10">
        <h3>Leave a comment</h3>
        @if (session('message'))
            <div class="alert alert-success">
                {{ session('message') }}
            </div>
        @endif
        {!! Form::open(['route' => ['blog.comments', $post->slug]]) !!}
        <form>
            <div class="form-group required {{ $errors->has('author_name') ? 'has-error' : '' }}">
                <label for="name">Name</label>
                {!! Form::text('author_name', null, ['class' => 'form-control']) !!}
                @if ($errors->has('author_name'))
                    <span class="help-block">{{ $errors->first('author_name') }}</span>
                @endif
            </div>
            <div class="form-group required {{ $errors->has('author_email') ? 'has-error' : '' }}">
                <label for="email">Email</label>
                {!! Form::text('author_email', null, ['class' => 'form-control']) !!}
                @if ($errors->has('author_email'))
                    <span class="help-block">{{ $errors->first('author_email') }}</span>
                @endif
            </div>
            <div class="form-group">
                <label for="website">Website</label>
                {!! Form::text('author_url', null, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group required {{ $errors->has('body') ? 'has-error' : '' }}">
                <label for="comment">Comment</label>
                {!! Form::textarea('body', null, ['rows' => 5, 'class' => 'form-control']) !!}
                @if ($errors->has('body'))
                    <span class="help-block">{{ $errors->first('body') }}</span>
                @endif
            </div>
            <div class="clearfix">
                <div class="pull-left">
                    <button type="submit" class="btn btn-lg btn-success">Submit</button>
                </div>
                <div class="pull-right">
                    <p class="text-muted">
                        <span class="required">*</span>
                        <em>Indicates required fields</em>
                    </p>
                </div>
            </div>
        </form>
        {!! Form::close() !!}
    </div>

</article>

resources/views/blog/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                @if (!$posts->count())
                    <div class="alert alert-warning">
                        <p>Nothing Found</p>
                    </div>
                @else
                    @include('blog.alert')
                    @foreach($posts as $post)
                        <article class="post-item">
                            @if ($post->image_url)
                                <div class="post-item-image">
                                    <a href="{{ route('blog.show', $post->slug) }}">
                                        <img src="{{ $post->image_url }}" alt="">
                                    </a>
                                </div>
                            @endif
                            <div class="post-item-body">
                                <div class="padding-10">
                                    <h2><a href="{{ route('blog.show', $post->slug) }}">{{ $post->title }}</a>
                                    </h2>
                                    <p>{!! $post->excerpt_html !!}</p>
                                </div>

                                <div class="post-meta padding-10 clearfix">
                                    <div class="pull-left">
                                        <ul class="post-meta-group">
                                            <li><i class="fa fa-user"></i><a
                                                    href="{{ route('blog.author', $post->author->slug) }}"> {{ $post->author->name }}</a>
                                            </li>
                                            <li><i class="fa fa-clock-o"></i>
                                                <time> {{ $post->date }}</time>
                                            </li>
                                            <li><i class="fa fa-folder"></i><a
                                                    href="{{ route('blog.category', $post->category->slug) }}">
                                                    {{ $post->category->title }}</a></li>
                                            <li><i class="fa fa-tag"></i>
                                                {!! $post->tags_html !!}
                                            </li>
                                            <li><i class="fa fa-comments"></i><a
                                                    href="{{ route('blog.show', $post->slug) }}#post-comments">{{ $post->commentsNumber() }}</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{{ route('blog.show', $post->slug) }}">Continue Reading &raquo;</a>
                                    </div>
                                </div>
                            </div>
                        </article>
                    @endforeach
                    <nav>
                        {{ $posts->appends(request()->only(['term', 'month', 'year']))->links() }}
                    </nav>
                @endif
            </div>
            <div class="col-md-4">
                @include('layouts.sidebar')
            </div>
        </div>
    </div>
@endsection

resources/views/blog/show.blade.php
@extends('layouts.main')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <article class="post-item post-detail">
                    @if ($post->image_url)
                        <div class="post-item-image">
                            <img src="{{ $post->image_url }}" alt="">
                        </div>
                    @endif
                    <div class="post-item-body">
                        <div class="padding-10">
                            <h1>{{ $post->title }}</h1>

                            <div class="post-meta no-border">
                                <ul class="post-meta-group">
                                    <li><i class="fa fa-user"></i><a
                                            href="{{ route('blog.author', $post->author->slug) }}"> {{ $post->author->name }}</a>
                                    </li>
                                    <li><i class="fa fa-clock-o"></i>
                                        <time> {{ $post->date }}</time>
                                    </li>
                                    <li><i class="fa fa-folder"></i><a
                                            href="{{ route('blog.category', $post->category->slug) }}">
                                            {{ $post->category->title }}</a></li>
                                    <li><i class="fa fa-tag"></i>
                                        {!! $post->tags_html !!}
                                    </li>
                                    <li><i class="fa fa-comments"></i><a href="#post-comments">{{ $post->commentsNumber() }}</a></li>
                                </ul>
                            </div>

                            {!! $post->body_html  !!}
                        </div>
                    </div>
                </article>

                <article class="post-author padding-10">
                    <div class="media">
                        <div class="media-left">
                            <a href="{{ route('blog.author', $post->author->slug) }}">
                                <img width="100" height="100" alt="{{ $post->author->name }}" src="{{ $post->author->gravatar() }}"
                                     class="media-object">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading"><a
                                    href="{{ route('blog.author', $post->author->slug) }}">{{ $post->author->name }}</a>
                            </h4>
                            <div class="post-author-count">
                                <a href="{{ route('blog.author', $post->author->slug) }}">
                                    <i class="fa fa-clone"></i>
                                    @php $postCount = $post->author->posts->count(); @endphp
                                    {{ $postCount }} {{ Str::plural('posts', $postCount) }}
                                </a>
                            </div>
                            <p>{!! $post->author->bio_html  !!}</p>
                        </div>
                    </div>
                </article>

                @include('blog.comments')
            </div>
            <div class="col-md-4">
                @include('layouts.sidebar')
            </div>
        </div>
    </div>
@endsection